### ISSUE TITLE
Matplot windows in main window

### ISSUE THREAD

**Issue by stejsle1** [stejsle1/semestralni_prace_PYT#1]
Ahoj, 
mam za ukol rozsireni WaTor ukolu -> optimalizace + graf.
Mam problem vlozit graf do pripraveneho layout z Designeru. Poradne nevim, co za okno by melo oznacovat budouci graf (Widget, Frame, ...). Nasla jsem navody, jak umistovat graf z matplotlibu, ale vetsina pocita s tim, ze plocha neni predpripravena v Designeru (graf pak tvori cele okno). Chtela bych se zeptat, jak v Designeru oznacit plochu, kde chci mit graf, a jak pak graf vlozit do plochy (nasla jsem tridy a moduly jako FigureCanvas, matplotlib.pyplot, matplotlib.figure.Figure, ale nevim, jak je spravne vlozit do Widgetu)?

**Comment by hroncok** [comment]
A ten graf, co tvoří celé okno, je widget? Pak by měl jít vložit do layoutu.

Edit: FigureCanvas je QWidget.

**Comment by hroncok** [comment]
FigureCanvas je QWidget.

**Comment by hroncok** [comment]
Něco jako:

```python
layout = window.findChild(QtWidgets.QHBoxLayout, 'myLayout')
canvas = MyMplCanvas(...)  # https://matplotlib.org/examples/user_interfaces/embedding_in_qt5.html
layout.addWidget(canvas)
```

**Comment by stejsle1** [comment]
Diky, zkusim

**Comment by stejsle1** [comment]
Diky moc, funguje (predtim jsem zkousela stejnou verzi, ale bez tridy MyMplCanvas a neslo to).
