### ISSUE TITLE
Verze projektu?

### ISSUE THREAD

**Issue by stejsle1** [stejsle1/semestralni_prace_PYT#2]
Ahoj, 
napadlo me, ze kdyz je to projekt staveny na projektu ze semestru, ktery se postupne dostal az do verze 0.3, bude lepsi projekt verzovat klasicky od 0.1 nebo pokracovat 0.4 a vlozit do README odkaz na Github projekt WaTor (ze semestru)?

**Comment by hroncok** [comment]
Já bych jel 0.4, ale důležité to není.
